spring.application.name=odoc

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.xlqjjiondntwemoajmos
spring.datasource.password=2026odoc123$

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.anything.odoc.domain

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

logging.level.org.mybatis=DEBUG
logging.level.org.apache.ibatis=DEBUG

# ?? ???? ?? (30m=30?, 1h=1??)
server.servlet.session.timeout=1h

# http-only: ??????? ???? ? ?? ?? ????
# secure: HTTPS??? ?? ??? ??
# same-site: ?? ??? ???? ??? ??? ??

# ?? ??? ?? ?? (true=HTTPS/false=HTTP)
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax

# ?? ??? ?? ??
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.secure=false
#server.servlet.session.cookie.same-site=lax