spring.application.name=odoc

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xlqjjiondntwemoajmos
spring.datasource.password=2026odoc123$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.anything.odoc.domain

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

logging.level.org.mybatis=DEBUG
logging.level.org.apache.ibatis=DEBUG